spring:
  application:
    name: "UserManagerService"
    datasource:
    url: jdbc:h2:mem:usersdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      operationsSorter: method

security:
  jwt:
    apiKey: 08942409d601fc0398683ffe60cf683f685d547c685ee12aecf602a99338cd5e
    expiration: 3600000 # 1 hour in milliseconds

config:
  user:
    domain : 'dominio.cl'
  password:
    regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8, }$'
    errorMessage: 'Password must contain at least 8 characters'

